{{ if .Values.sslSecrets.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include kafka.sslSecrets.fullname . }}
type: Opaque
data:
        {{ with .Values.sslSecrets.broker }}
        kafka.broker.truststore.jks: {{ required "Truststore is required" .truststoreBase64 }}
        kafka.broker.truststore.passwd: {{ .truststorePassword | b64enc }}

        kafka.broker.keystore.jks: {{ required "Keystore is required" .keystoreBase64 }}
        kafka.broker.keystore.passwd: {{ .keystorePassword | b64enc }}
        kafka.broker.key.passwd: {{ .keyPassword | b64enc }}
        {{ end }}

        {{ with .Values.sslSecrets.jksClient }}
        kafka.jksClient.truststore.jks: {{ .truststoreBase64 }}
        kafka.jksClient.truststore.passwd: {{ .truststorePassword | b64enc }}

        kafka.jksClient.keystore.jks: {{ .keystoreBase64 }}
        kafka.jksClient.keystore.passwd: {{ .keystorePassword | b64enc }}
        kafka.jksClient.key.passwd: {{ .keyPassword | b64enc }}
        {{ end }}

        kafka.ca.crt: {{ required "CA cert is required" .Values.sslSecrets.caBase64 }}

        {{ with .Values.sslSecrets.client }}
        kafka.client.crt: {{ .certBase64 }}
        kafka.client.key: {{ .keyBase64 }}
        kafka.client.key.passwd: {{ .keyPassword | b64enc }}
        {{ end }}
{{ end }}
